(part "TPS7A0233PDBVR"
    (packageRef "SOT95P280X145-5N")
    (interface
        (port "1" (symbPinId 1) (portName "IN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "EN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TPS7A0233PDBVR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS7A0233PDBVR?qs=OlC7AqGiEDmMDf5GlW%2FWnQ%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS7A0233PDBVR")
    (property "Description" "Low-Dropout Voltage Regulator")
    (property "Datasheet_Link" "https://www.ti.com/lit/gpn/TPS7A02")
    (property "symbolName1" "TPS7A0233PDBVR")
)
